### ISSUE TITLE
Feature: allow to define response code

### ISSUE THREAD

**Issue by esteban-serfe** [Marketionist/node-testing-server#41]
I would love to use this on my CodeceptJS test cases but need to be able to define the response code and the response type when configuring the server before the test case.

on the code I don't see that as a possible option. Is there a way to enable that?

**Comment by Marketionist** [comment]
I'll be adding this feature soon. Thanks for the the suggestion @esteban-serfe!

**Comment by Marketionist** [comment]
@esteban-serfe please try a new version of node-testing-server - `1.6.0`.

Here is the example of configuration that you can use if you want to specify a status code that will be returned by the page:

```javascript
let { nodeTestingServer } = require('node-testing-server');

// Settings for node testing server
nodeTestingServer.config = {
    hostname: 'localhost',
    port: 3001,
    logsEnabled: 0,
    pages: {
        '/test.html': {
            pageStatusCode: 201,
            pageBody: `<ul class="items">
                        <li>First</li>
                        <li>Second</li>
                        <li>Third</li>
                        <li>Fourth</li>
                        <li>Fifth</li>
                        <li>Sixth</li>
                        <li>Seventh</li>
                        <li>Eighth</li>
                        <li>Ninth</li>
                        <li>Tenth</li>
                    </ul>`
        }
    }
};
```

**Comment by esteban-serfe** [comment]
> @esteban-serfe please try a new version of node-testing-server - `1.6.0`.
> 
> Here is the example of configuration that you can use if you want to specify a status code that will be returned by the page:
> 
> ```js
> let { nodeTestingServer } = require('node-testing-server');
> 
> // Settings for node testing server
> nodeTestingServer.config = {
>     hostname: 'localhost',
>     port: 3001,
>     logsEnabled: 0,
>     pages: {
>         '/test.html': {
>             pageStatusCode: 201,
>             pageBody: `<ul class="items">
>                         <li>First</li>
>                         <li>Second</li>
>                         <li>Third</li>
>                         <li>Fourth</li>
>                         <li>Fifth</li>
>                         <li>Sixth</li>
>                         <li>Seventh</li>
>                         <li>Eighth</li>
>                         <li>Ninth</li>
>                         <li>Tenth</li>
>                     </ul>`
>         }
>     }
> };
> ```

As soon as I get the chance to run the tests that needs this feature will test it out and let you know.... The project has been dormant for some time now...

Thanks for the help getting this!

**Comment by Marketionist** [comment]
Sounds good, closing this issue - @esteban-serfe feel free to create a new one for any feature requests/updates. Also please consider clicking on the **★ Star** at the top right corner of https://github.com/Marketionist/node-testing-server to show some love and keep track of this repository.
